version: '3.8'

services:
  golang-app:
    build: ./golang
    ports:
      - "8080:8080"
    environment:
      - JWT_SECRET=your-secret-key
    networks:
      - security-network

  typescript-app:
    build: ./typescript
    ports:
      - "3000:3000"
    environment:
      - JWT_SECRET=your-secret-key
    networks:
      - security-network

  java-app:
    build: ./java
    ports:
      - "8081:8080"
    environment:
      - JWT_SECRET=your-secret-key
    networks:
      - security-network

  juice-shop:
    image: bkimminich/juice-shop:latest
    ports:
      - "3002:3000"
    environment:
      - NODE_ENV=test
    networks:
      - security-network

  security-dashboard:
    image: grafana/grafana:latest
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
    networks:
      - security-network

networks:
  security-network:
    driver: bridge 