version: '3.8'

services:
  golang-app:
    build: 
      context: ./golang
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - JWT_SECRET=${JWT_SECRET:-your-secret-key}
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - security-network
    restart: unless-stopped

  typescript-app:
    build: 
      context: ./typescript
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - JWT_SECRET=${JWT_SECRET:-your-secret-key}
      - NODE_ENV=production
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - security-network
    restart: unless-stopped

  java-app:
    build: 
      context: ./java
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    environment:
      - JWT_SECRET=${JWT_SECRET:-your-secret-key}
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - security-network
    restart: unless-stopped

  juice-shop:
    image: bkimminich/juice-shop:latest
    ports:
      - "3002:3000"
    environment:
      - NODE_ENV=test
      - JWT_SECRET=${JWT_SECRET:-your-secret-key}
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - security-network
    restart: unless-stopped

  security-dashboard:
    image: grafana/grafana:latest
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD:-admin}
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER:-admin}
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_SERVER_HTTP_PORT=3000
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - grafana-storage:/var/lib/grafana
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - security-network
    restart: unless-stopped

networks:
  security-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16

volumes:
  grafana-storage:
    driver: local 